### ISSUE TITLE
entangled chalice makes water to blood

### ISSUE THREAD

**Issue by JokerReaper** [rubensworks/EvilCraft#191]
i came across this while learning how to use the chalices in my test map, i was having an issue with getting them to change the fluids that they transfered, & i out of curiosity used the blood extractor on a chalice that had blood in it before, i dont think had anything really to do with it but, i used the extractor on them after i got them to transfer water, when clicked to collect it like i would any blood source it said water was in it, but when i went to fill a hole i made to get rid of the contents it was blood, i tested it on the chalices again just to see, & sure enough it happened every time, but when i went to use it on a standing water source near by it did not pick up any fluid at all. heres a screenshot
http://i59.tinypic.com/4jp6qd.png

**Comment by rubensworks** [comment]
Thanks for reporting, I'll have a look at it asap.

**Comment by rubensworks** [comment]
@JokerReaper Could you give me some more details on the problems you had with getting them to change the fluids they transfer? Or do I misunderstand and is this actually the same issue as the Blood Extractor allowing you to change Water into Blood?
Are you using the latest version (0.7.1)?

**Comment by JokerReaper** [comment]
its the latest version, 1.7.10-0.7.1b, the extractor changing water into blood & the chalice problem are 2 different problems, i would have a liquid in the chalices, like blood, one or both would be on the ground & i would empty them, ie dark tank, or extractor, this is where i used the extractor to remove water from them while they were on the ground, but when i would pick up the chalices "empty" then place them to start taking another fluid, "water, or blood" ive had issues with oil from thermal expansion, but the chalice i would place would refill with the previous fluids & would take some messing with to start taking in the other liquid, im not sure if its something im doing or if its cause my mod pack

minecraft version 1.7.10
[1.7.10]bspkrsCore-universal-6.15
adventurebackpack-1.7.10-0.7.5
Baubles-1.7.10-1.0.1.8
buildcraft-6.2.0
CodeChickenCore-1.7.10-1.0.4.29-universal
CodeChickenLib-1.7.10-1.1.1.110-universal
CoFHCore-[1.7.10]3.0.0B9-40
Damage-Indicators-Mod-1.7.10
EvilCraft-1.7.10-0.7.1b
FamiliarsAPI-1.7.10
FamiliarsDefaultMobPack-1.7.10
FamiliarsExtendedFamPack-1.7.10
FamiliarsHerobrineFamPack-1.7.10
Flans Mod-1.7.10-4.8.0 modern warfare, guns only
iChun-Util-Mod-1.7.10
ironchest-1.7.10-6.0.62.742-universal
LoK_SoulReaver-1.7.10(0.4.8)
NotEnoughItems-1.7.10-1.0.3.74-universal
OptiFine_1.7.10_HD_B4
Reis-Minimap-Mod-1.7.10
Thaumcraft-1.7.10-4.2.1.4
thaumcraftneiplugin-1.7.10-1.6a
ThermalExpansion-[1.7.10]4.0.0B8-23
ThermalFoundation-[1.7.10]1.0.0RC1-13
Tree-Capitator-Mod-1.7.2-1.7.9
mychunkloader-1710.01
mystcraft-1.7.10-0.11.0.00

**Comment by rubensworks** [comment]
All issues you've mentioned should be fixed. If you want, you can try out the latest dev build (245) which contains fixes for these (and other) issues, just to make sure it works correctly now.
Latest build: https://drone.io/github.com/rubensworks/EvilCraft/files

**Comment by JokerReaper** [comment]
ive downloaded the 246 dev, & tried out the chalices they are working as they should, no problems with switching between fluids, but the extractor is still changing water to blood, it also seems to do it with any fluid in the chalices, but it seems to work with dark tanks as well, it does work on the buildcraft tanks but can only remove 1000 mb from them even if i use blood in the tanks "full" i can only take 1000 mb from them, but thats buildcrafts problem, but i can take that 1000mb of other fluids & turn it to blood, its only when the fluids are standing expect blood ofcourse, that i can not pick them up with the extractor, one other thing if theres a standing pool or source of fluid, you can take blood in the extractor & im thinking other fluid as well & transform the pool to blood, i know im finding all kinds of problems im sorry for that

**Comment by rubensworks** [comment]
I'll look into it tomorrow. And please keep reporting any problems you find, it can only help with making this mod more stable ;)

**Comment by rubensworks** [comment]
Just thought about this, but are you still using the old Blood Extractors you used while first testing this? Because they might have become corrupted (what caused them to be able to pickup all fluids), can you try cheating in a new Blood Extractor and see if the problem persists?

**Comment by JokerReaper** [comment]
i used another extractor & yes it does not fill itself with another fluid, ive tested it on other sources, but the changing of other pool or sources of standing fluids does still happen

**Comment by rubensworks** [comment]
Ok, thanks for checking, I'll look into it asap!

**Comment by JokerReaper** [comment]
yeah np, if there's anything else you want me to test, i'll be happy to, i have the free time

**Comment by rubensworks** [comment]
I just checked and the last issue you mentioned does not seem to be a bug, it's intended behavior. It acts just like emptying buckets in standing fluids, and it correctly drains the Blood Extractor when doing so, unless you are in creative mode of course.

If you are interested, I can provide you with test version of this mod before new major releases will be released, always looking for more testers. If so, you give me your email address here, or DM it to me on twitter @rubensworks or @kroesermc

**Comment by JokerReaper** [comment]
here's my email address its the only one i really use or check eagles.joker@gmail.com

**Comment by JokerReaper** [comment]
idk if you'll be getting this email or not but im sending you my email
about testing, & a suggestion, which idk if it can be done or not, just a
suggestion about the chalices, i didnt know where to put it or send it, but
here goes, possibly making the chalices a chunk loader, just so it loads
the pipe or machine its near. reason why is that im play single player, &
for certain things like buildcraft & thermal expansion, when i leave the
area to go do something else it stops, only thing that keeps itself loaded
is the quarry from buildcraft, everything else doesnt keep loading, i had
to install a chunk loader mod just for that, its a simple mod, but i have
to cheat the block in, & i dont like doing that, unless there's a major
issue with the game that i have to fix.

my email is eagles.joker@gmail.com let me know if youve gotten this email,
& what you think about my suggestion

ps im really loving this mod its been alot of fun messing around with it
lol
